/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CheckboxOption: typeof import('./src/components/options/CheckboxOption.vue')['default']
    ConfigSidebar: typeof import('./src/components/ConfigSidebar.vue')['default']
    DropdownOption: typeof import('./src/components/options/DropdownOption.vue')['default']
    IHeroiconsArrowDownTray20Solid: typeof import('~icons/heroicons/arrow-down-tray20-solid')['default']
    IHeroiconsBars3Solid: typeof import('~icons/heroicons/bars3-solid')['default']
    IHeroiconsCheck20Solid: typeof import('~icons/heroicons/check20-solid')['default']
    IHeroiconsExclamationCircle: typeof import('~icons/heroicons/exclamation-circle')['default']
    IHeroiconsExclamationTriangle: typeof import('~icons/heroicons/exclamation-triangle')['default']
    IHeroiconsInformationCircle: typeof import('~icons/heroicons/information-circle')['default']
    IHeroiconsLink20Solid: typeof import('~icons/heroicons/link20-solid')['default']
    IHeroiconsMagnifyingGlass20Solid: typeof import('~icons/heroicons/magnifying-glass20-solid')['default']
    IHeroiconsXCircle: typeof import('~icons/heroicons/x-circle')['default']
    IHeroiconsXMark: typeof import('~icons/heroicons/x-mark')['default']
    ISimpleIconsGithub: typeof import('~icons/simple-icons/github')['default']
    NumberOption: typeof import('./src/components/options/NumberOption.vue')['default']
    PluginOptionsCard: typeof import('./src/components/PluginOptionsCard.vue')['default']
    ProjectDescription: typeof import('./src/components/ProjectDescription.vue')['default']
    RadioOption: typeof import('./src/components/options/RadioOption.vue')['default']
    ScriptPreview: typeof import('./src/components/ScriptPreview.vue')['default']
    TextOption: typeof import('./src/components/options/TextOption.vue')['default']
  }
}
